### ISSUE TITLE
wont load at all 

### ISSUE THREAD

**Issue by xg787** [CorgiTaco-MC/CorgiLib#38]
wont load at all
CorgiLib 4.0.2.0
forge 47.2.17

Exception in thread "main" java.lang.module.ResolutionException: Module minecraft reads more than one module named com.electronwill.nightconfig.core
	at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
	at java.base/java.lang.module.Resolver.finish(Unknown Source)
	at java.base/java.lang.module.Configuration.<init>(Unknown Source)
	at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by krzj** [comment]
![Uploading 8A82C479E051DB313C290900471A431A.png…]()

**Comment by krzj** [comment]
![8A82C479E051DB313C290900471A431A](https://github.com/user-attachments/assets/5acd5abb-f540-4bbf-80ba-8230a47234ef)
