### ISSUE TITLE
Unable to start due to `ResolutionException` being thrown

### ISSUE THREAD

**Issue by andriihorpenko** [CorgiTaco-MC/CorgiLib#40]
### Description
Something has broken in one of the latest updates of CorgiLib.
I had CorgiLib 4.0.1.3 prior to this issue, which was working just fine.

### Exception
```
Exception in thread "main" java.lang.module.ResolutionException: Module resourcefullib reads more than one module named com.electronwill.nightconfig.toml
        at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
        at java.base/java.lang.module.Resolver.finish(Unknown Source)
        at java.base/java.lang.module.Configuration.<init>(Unknown Source)
        at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```

**Comment by ConnorNMoran** [comment]
I have this exact problem too. Confused the hell out of me for a while.

**Comment by nanonestor** [comment]
Issue found - the actually built mod file 4.0.2.0 ships - META-INF\jars\core-3.6.7.jar - inside, which causes the conflict and issue.

For now, downgrading Corgilib to the next older version works until the author fixes this.

**Comment by rmyj** [comment]
nice work @nanonestor

**Comment by ratemisia** [comment]
Duplicate copies of TheElectronWill's project https://github.com/TheElectronWill/night-config have shown up in several issues with the latest version: This issue, #41 and #38 are all duplicates. I would strongly encourage @CorgiTaco or @JT122406 to remove the latest 4.0.2.0 version of CorgiLib from all mod platforms (CurseForge and Modrinth) until the duplicate copy of Night Config can be removed with a bugfix/update, as that version of the library _will never load_ along with Forge or NeoForge. This is a very urgent issue that is completely breaking a lot of games and packs - I would suggest that rolling back to 4.0.1.3 is preferable to shipping a version that will be inoperable for many players.

**Comment by JT122406** [comment]
4.0.2.0 wasn't meant to be published yet, this issue has been fixed in my latest pr

**Comment by ratemisia** [comment]
Good to hear that you are aware of this issue, thanks for the rapid response. Looking forward to a fix.

**Comment by andriihorpenko** [comment]
Resolved in the latest release
